pattern:
    type: acircles  # options: chessboard, circles, acircles
    size: 11x4  # columns x rows
    square: 0.04  # square size in meters

blob_detector:  # only for circles/acircles patterns
    filter_by_area: True
    max_area: 10000000  # pixels
    min_area: 100  # pixels
    filter_by_circularity: True
    max_circularity: 1.0
    min_circularity: 0.7
    # filter_by_color: True
    # color: 0  # scalar opencv color
    filter_by_convexity: True
    max_convexity: 1.0
    min_convexity: 0.8
    # filter_by_inertia: True
    # max_inertia_ratio: 3.4028234663852886e+38
    # min_inertia_ratio: 0.1

    max_threshold: 200
    min_threshold: 0
    threshold_step: 10
    min_repeatability: 3

    min_dist_between_blobs: 5

